### ISSUE TITLE
Auto sync references from .csproj file.

### ISSUE THREAD

**Issue by Gandifil** [Ellpeck/Contentless#3]
Hi! Firstly, thanks you for this beautiful tool!

Secondly, I often work with different versions of `Extended.Pipeline` and don't work inside C:// logical disks. So i must often change a 'References' block in `Content.mgcb`. What do you think about feature to manage references, restore its from project file?

**Comment by Ellpeck** [comment]
I actually really like this idea! I'll have to investigate whether doing this is possible, but I assume there's some way to figure out what assemblies an attached project file is referencing and search those for custom content importers and stuff.

Unfortunately, I don't know if the implementation I have in mind will necessarily solve your problem though. One of the key philosophies is that Contentless only ever *adds* to the content file, but doesn't remove or edit any existing lines. This means that changing existing references would not be within the bounds Contentless.

That being said, there was also another suggestion related to editing existing parts of the content file (#2), so maybe these features could all be disabled by default, but enable-able through the Contentless.json file. I'll think about it!

**Comment by Gandifil** [comment]
I'm going to implement it and send PR to you, ok?
I don't see a problem of philosophies, because it's not about about removing content item, it's about sync references between .mgcb file and .csproj. And yes, I think to make it optionable is a good idea.

**Comment by Ellpeck** [comment]
Hi! I plan on working on Contentless again next week, so I'll be implementing this feature myself shortly. If you're still interested in working on it yourself and submitting a pull request before that, please feel free to!

*Edit: Unfortunately, I don't think I'll be able to get around to this very soon after all, so feel free to submit your pull request like you suggested!*
