### ISSUE TITLE
Order of task processing

### ISSUE THREAD

**Issue by Gandifil** [Ellpeck/Contentless#5]
I have paid attention to ordering of `Contentless `build task. Sometimes it run _after_ `MGCB`. It means you need rebuild project two times for updating content. It may fixed easily.
[https://docs.monogame.net/articles/tools/mgcb.html](url) (read last title)

**Comment by Ellpeck** [comment]
The tasks that MonoGame uses have changed a lot throughout the last few years, especially with the transition from .NET Framework to .NET (Core). That's why this inconsistency exists right now. It should be an easy fix though, as you said!

**Comment by Gandifil** [comment]
Additional point: I've faced a trouble now. Library must check that first argument are *.mgcb now, because if `MonoGameContentReference` is missed, msbuild try to run 'contentless *csproj", and contentless corrupts `*.csproj`. Better fix that.

If you ask why i do that: I try run Contentless without `MonoGame.Content.Builder.Task`, inside which `MonoGameContentReference` variable.

**Comment by Ellpeck** [comment]
Thanks for letting me know! I'll get around to fixing that ASAP :)
