### ISSUE TITLE
Contentless.targets throws error when project directory contains whitespace

### ISSUE THREAD

**Issue by MegaInferno94** [Ellpeck/Contentless#9]
When using this package in a project directory with whitespace, an error is thrown.
<img width="481" alt="error" src="https://github.com/user-attachments/assets/34b04da7-e6a3-41e7-a4b1-01193a104c3c">

The problem seems to arise in line 3, which is fixed when $(MSBuildProjectFullPath) is wrapped in &quot; characters.
<img width="290" alt="whitespace_fix" src="https://github.com/user-attachments/assets/94025ae6-a31b-4783-9560-0e5748e21827">

Admittedly, I don't know anything about target files, so the current command might have been written purposefully as-is for security or something. Is this something that is possible to be fixed in a future Nuget package version?

Fantastic work on this project so far though - really love what you're doing here!

**Comment by Ellpeck** [comment]
Hi! This is indeed a bug, and the fix you're describing seems to pretty much be what I would've also done. 

If you have a chance and are versed with how to create pull requests and whatnot, it'd be great if you submitted your changes as one :) If not, I'll do it next time I get a chance to work on the project.
